image:
  name: hashicorp/terraform:1.1.1
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  -  rm -rf .terraform
  -  terraform --version
  -  echo $SERVICEACCOUNT
  -  echo $SERVICEACCOUNT | base64 -d > terraform.json
  -  terraform init

stages:
    - validate
    - plan
    - apply

validate:
   stage: validate
   script:
     - terraform validate

plan:
   stage: plan
   script:
     - terraform plan -out "planfile" -var="gitlab_runner_registration_token=$RUNNER_TOKEN" -var="project_id=$PROJECTID"
   dependencies:
     - validate
   artifacts:
     paths:
       - planfile

apply:
   stage: apply
   script:
     - terraform apply -var="gitlab_runner_registration_token=$RUNNER_TOKEN" -var="project_id=$PROJECTID" -input=false "planfile"
   dependencies:
     - plan
   when: manual
